### ISSUE TITLE
How do you change the league level

### ISSUE THREAD

**Issue by jpeg729** [csj/code-royale#4]
I tried compiling using 
```
mvn install dependency:copy-dependencies
```
and running using 
```
java -cp "target/code-royale-1.0-SNAPSHOT.jar:target/test-classes:target/dependency/*" Main -Dleague.level=4
```
but my bot looses every time it tries to build a tower or a mine.

**Comment by csj** [comment]
Hi there. Unfortunately I could only figure out how to read the current league from the provided SDK; I couldn't figure out how to manually set it on startup. To do a quick test you can short-circuit that branching stuff in the code, but to do it properly over the command line I think you would need to ask Julien from CG.
